### ISSUE TITLE
status errored

### ISSUE THREAD

**Issue by iostyle** [cmdboys/little-green-hat#1]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/22219146/54798672-b6f6a900-4c94-11e9-9535-81ffbde7c08c.png">

**Comment by iostyle** [comment]
kill pm2 
pm2 update

**Comment by iostyle** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/22219146/54798892-b4e11a00-4c95-11e9-9158-ca8e911476f0.png">

**Comment by iostyle** [comment]
![image](https://user-images.githubusercontent.com/22219146/54798931-dc37e700-4c95-11e9-9f8d-66465513ca73.png)

**Comment by Jon-Millent** [comment]
麻烦把error log贴一下😄

**Comment by iostyle** [comment]
update nodejs

**Comment by iostyle** [comment]
即使设置了高频率也没有使我变色😅 不知道是什么原因

**Comment by Jon-Millent** [comment]
看了看你的在正常运行，难道github commit fork别人的项目不列入计算（扎心了老铁）？尝试下创建一个新项目，把代码放进去，然后在操作一遍。

**Comment by iostyle** [comment]
咦？你的也挂了？
